modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT License"

[[mods]]
modId = "cobblextras"
version = "${version}"
displayName = "Cobblextras"
authors = "Jishuna"
description = '''
Miscellaneous extra features for the Cobblemon mod.
'''

[[mixins]]
config = "cobblextras.mixin.json"

[[dependencies.cobblextras]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblextras]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.182,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblextras]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.7.0,)"
ordering = "AFTER"
side = "BOTH"
